[build]
  command = "composer install && npm run build"
  publish = "public/build"

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = true