[build]
  command = "composer install && npm run build"
  publish = "public/build"

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "http://backend.example.com/:splat"
  status = 200
